---
# tasks file for roles/ftp_centos

- name: Centos FTP server
  yum:
    name: vsftpd
    state: latest
    update_cache: yes

- name: FTP server
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: FTP user
  user:
    name: '{{ user }}'
    password: '{{ ftp_pass }}'

- name: Access SSH via user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: SSHD Service
  service:
    name: sshd
    state: restarted
  when: successfully_denied.changed

- name: Default config file 
  copy:
    src: /etc/vsftpd/vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf.default
    remote_src: True

- name: FTP users
  replace:
    path: /etc/vsftpd/vsftpd.conf
    regexp: '#chroot_local_user=YES'
    replace: 'chroot_local_user=YES'

- name: FTP File config
  lineinfile:
    path: /etc/vsftpd/vsftpd.conf
    line: '{{ ftp_config }}'

- name: VSFTPD
  service:
    name: vsftpd
    state: restarted
