#Main Variable
prelim_exam: https://github.com/kkrvillavicencio-tip/sysad2-12021.git

username: kkrvillavicencio-tip

#ftp config
writable_chroot: allow_writeable_chroot=YES
ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"

ftp_debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlsv1=YES\nssl_sslv2=NO\nssl_sslv3=NO"

user: ftpadmin
ftp_pass: $5$EKedwA6G6L$oTMqsot3r/lvUbPmV2CEW9awAhFkoC7IkicOwhPCrfC

#Nagios setup
user_pass: $5$e9C6aEun$nXI9dQ3x35Bkv1Gwgfl7FG2PqnSgQrnjYP7n./js6S4
admin_pass: kevincute
