---
# tasks file for roles/centos_nagios

- name: Centos dependencies
  yum:
    name:
      - httpd
      - gcc
      - glibc
      - glibc-common
      - gd-devel
      - perl
      - postfix
      - unzip
    state: latest
    update_cache: yes

- name: Centos HTTPD
  service:
    name: httpd
    state: started

- name: Nagios group 
  group:
    name: nagios
    state: present

- name: Nagios group
  group:
    name: nagcmd
    state: present

- name: Nagios user
  user:
    name: nagios
    shell: /bin/bash
    comment: nagios user
    group: nagios
    password: '{{ user_pass }}'

- name: HTTPD to Nagios group
  user:
    name: apache
    groups: nagios
    append: yes

- name: Nagios user group for external commands
  user:
    name: nagios
    groups: nagcmd
    append: yes

- name: Data user group for external commands
  user:
    name: www-data
    group: nagcmd
    append: yes

- name: Downloads directory
  file:
    path: /downloads
    state: directory

- name: Nagios download
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: Nagios Core
  unarchive:
    src: /downloads/nagios-4.2.1.tar.gz
    dest: /downloads
    remote_src: yes

- name: Virtual host directory
  file:
    path: /etc/httpd/conf.d
    state: directory

- name: Nagios script config
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
    chdir: /downloads/nagios-4.2.1

- name: Nagios Core compile
  make:
    chdir: /downloads/nagios-4.2.1
    target: all

- name: Binaries install
  make:
    chdir: /downloads/nagios-4.2.1
    target: install

- name: Init Script
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-daemoninit

- name: Sample config files
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: Set permissions
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: Nagios Web Interface
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: Exfoliation theme
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-exfoliation

- name: Installing classcui theme
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-classicui

- name: Htpasswd pip
  yum:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Htpasswd module
  pip:
    name: passlib
    state: latest

- name: Nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ admin_pass }}'

- name: Apache service
  service:
    name: httpd
    state: reloaded

- name: Nagios service
  shell: '/etc/init.d/nagios start'
