---
# tasks file for roles/suse_nagios
- name: OpenSUSE dependencies
  zypper:
    name:
      - apache2
      - gcc
      - glibc
      - gd
      - perl
      - php7
      - apache2-mod_php7
      - unzip
    state: latest

- name: PHP7
  shell: 'a2enmod php7'

- name: Nagios group
  group:
    name: nagios
    state: present

- name: Nagios group
  group:
    name: nagcmd
    state: present

- name: Nagios group
  group:
    name: nagadmin
    state: present

- name: Nagios user
  user:
    name: nagios
    comment: nagios user
    group: nagadmin

- name: Run user group for external command
  user:
    name: wwwrun
    groups: nagadmin
    append: yes

- name: Downloads directory
  file:
    path: /downloads
    state: directory

- name: Nagios
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: Nagios core
  unarchive:
    src: /downloads/nagios-4.2.1.tar.gz
    dest: /downloads
    remote_src: yes

- name: Virtual host directory
  file:
    path: /etc/httpd/conf.d
    state: directory

- name: Nagios script config
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
    chdir: /downloads/nagios-4.2.1

- name: Nagios core
  make:
    chdir: /downloads/nagios-4.2.1
    target: all

- name: Binaries
  make:
    chdir: /downloads/nagios-4.2.1
    target: install

- name: Init script
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-init

- name: Sample config files
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: Set permissions
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: Nagios web interface
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: Htpasswd pip
  zypper:
    name: python3-pip
    state: latest

- name: Htpasswd module
  pip:
    name: passlib
    state: latest

- name: Nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ admin_pass }}'

- name: Apache service
  service:
    name: apache2
    state: reloaded

