---
# tasks file for roles/debian_clone
- name: Git on Debian
  apt:
    name: git
    state: latest

- name: Debian Prelim-exam branch 
  git:
    repo: '{{ prelim_exam }}'
    dest: ./prelim-exam
    version: prelim-exam
